print("[-----------------------------------------------]")
print("")
print("Binds:")
print("U                         Open and close output")
print("RShift                    Fill suggestion")
print(";                         Focus on CMDBar")
print("Q                         Open and Close")
print("LShift+Bksp               Clear CMDBar")
print("")
print(".cmds                     List commands")
print("")
print("[-----------------------------------------------]")

loadstring(game:HttpGet("https://raw.githubusercontent.com/CMD-X/CMD-X/master/CMD-X", true))()